<?php

/**
 * @file
 * Allows to send messages to all members of a role.
 */

/**
 * Implements hook_perm().
 */
function privatemsg_roles_permission() {
  $permissions = array(
    'write privatemsg to roles' => array(
      'title' => t('Write private message to all roles'),
      'description' => t('Allows to write messages to all users which belong to a specific role.'),
    ),
    'view roles recipients' => array(
      'title' => t('View roles recipients'),
      'description' => t('Ability to view roles recipients and the name of these roles.'),
    ),
  );

  foreach (user_roles(TRUE) as $role_name => $role_label) {
    $permissions['write privatemsg to role ' . $role_name] = array(
      'title' => t('Write private messages to role %role', array('%role' => $role_label)),
      'description' => t('Allows to write messages to all users which belong to a specific role.'),
    );
  }
  return $permissions;
}

/**
 * Implements hook_config_info().
 */
function privatemsg_roles_config_info() {
  $prefixes['privatemsg_roles.settings'] = array(
    'label' => t('Private message roles settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

function privatemsg_roles_theme() {
  return array(
    'privatemsg_roles_format' => array(
      'variables' => array('recipient' => NULL, 'options' => array()),
    ),
  );
}

/**
 * Implements hook_privatemsg_recipient_type_info().
 */
function privatemsg_roles_privatemsg_recipient_type_info() {
  return array(
    'role' => array(
      'name' => t('Role'),
      'description' => t('Enter the name of a role to write a message to all users which have that role. Example: authenticated user.'),
      'load' => 'privatemsg_roles_load_multiple',
      'format' => 'privatemsg_roles_format',
      'autocomplete' => 'privatemsg_roles_autocomplete',
      'generate recipients' => 'privatemsg_roles_load_recipients',
      'count' => 'privatemsg_roles_count_recipients',
      'write callback' => 'privatemsg_roles_write_access',
      'view access' => 'view roles recipients',
    ),
  );
}

/**
 * Write permission check for roles recipients.
 */
function privatemsg_roles_write_access($recipient) {

  // Check if user has permission to write to all roles.
  if (user_access('write privatemsg to roles')) {
    return TRUE;
  }

  if ($recipient) {
    if (empty($recipient->name)) {
      $recipients = privatemsg_roles_load_multiple(array($recipient->recipient), $recipient->type);
      $recipient = array_shift($recipients);
    }
    // Check permission for this recipient.
    return user_access('write privatemsg to role ' . $recipient->name);
  }
  // Check if user has permission to write at least one role.
  foreach (user_roles(TRUE) as $role_name => $role_label) {
    if (user_access('write privatemsg to role ' . $role_name)) {
      return TRUE;
    }
  }
  // No permission, return FALSE.
  return FALSE;
}

/**
 * Load a number of roles based on their role_id.
 *
 * @param array $rids
 *   Array of role ids.
 * @param string $type
 *   Recipient type.
 * @return array
 *   Array of role objects.
 */
function privatemsg_roles_load_multiple($rids, $type) {
  $config = config('privatemsg_roles.settings');
  $role_ids = $config->get('role_id');
  $roles = array();
  foreach ($rids as $rid) {
    if ($role_name = array_search($rid, $role_ids)) {
      $role = user_role_load($role_name);
      $role->type = 'role';
      $role->recipient = $rid;
    }
    $roles[privatemsg_recipient_key($role)] = $role;
  }

  return $roles;
}

/**
 * Format a role to be displayed as a recipient.
 */
function theme_privatemsg_roles_format($variables) {
  $role = $variables['recipient'];
  $options = $variables['options'];
  if (!empty($options['plain'])) {
    $name = $role->label;
    if (!empty($options['unique'])) {
      $name .= ' [role]';
    }
    return $name;
  }
  return t('%role (role)', array('%role' => $role->label));
}

/**
 * Loads users with a specific role.
 *
 * @param object $recipient
 * @param int $limit
 * @param int $offset
 *
 * @return array
 *   Array of recipient users.
 */
function privatemsg_roles_load_recipients($recipient, $limit, $offset) {
  $role_name = $recipient->name;
  if ($role_name == BACKDROP_AUTHENTICATED_ROLE) {
    $result = db_query_range('SELECT uid FROM {users} WHERE uid > 0 ORDER BY uid ASC', $offset, $limit);
  }
  else {
    $result = db_query_range('SELECT uid FROM {users_roles} WHERE role = :role ORDER BY uid ASC', $offset, $limit, array(':role' => $role_name));
  }

  return $result->fetchCol();
}

/**
 * Return the number of users which have a given role.
 *
 * @param object $recipient
 *
 * @return int
 */
function privatemsg_roles_count_recipients($recipient) {
  $role_name = $recipient->name;
  if ($role_name == BACKDROP_AUTHENTICATED_ROLE) {
    return db_query('SELECT COUNT(uid) FROM {users}')->fetchField();
  }
  else {
    return db_query('SELECT COUNT(uid) FROM {users_roles} WHERE role = :role', array(':role' => $role_name))->fetchField();
  }
}

/**
 * Determine if users exist with a role.
 *
 * @param string $role_name
 *
 * @return bool
 */
function privatemsg_roles_exist_users_with_role($role_name) {
  if ($role_name == BACKDROP_AUTHENTICATED_ROLE) {
    return TRUE;
  }
  else {
    return (bool) db_query('SELECT COUNT(uid) FROM {users_roles} WHERE role = :role', array(':role' => $role_name))->fetchField();
  }
}

/**
 * Provides autocomplete suggestions for roles.
 */
function privatemsg_roles_autocomplete($fragment, $names, $limit, $type) {
  $user_roles = user_roles(TRUE);

  $suggestions = array();
  foreach ($user_roles as $role_name => $role_label) {
    if (user_access('write privatemsg to roles') || user_access('write privatemsg to role ' . $role_name)) {
      if (stripos($role_label, $fragment) !== FALSE && !in_array($role_label, $names)) {
        if (privatemsg_roles_exist_users_with_role($role_name)) {
          $recipient = (object) array();
          $recipient->type = 'role';
          $recipient->recipient = _privatemsg_roles_get_role_id($role_name, TRUE);
          $recipient->name = $role_name;
          $recipient->label = $role_label;
          // Add to suggested list if so.
          $suggestions[privatemsg_recipient_key($recipient)] = $recipient;
          if (count($suggestions) >= $limit) {
            return $suggestions;
          }
        }
      }
    }
  }
  return $suggestions;
}

/**
 * Implements hook_privatemsg_name_lookup().
 */
function privatemsg_roles_privatemsg_name_lookup($string) {
  // Remove optional role specifier.
  $string = str_replace(t('[role]'), '', $string);
  $name = trim($string);
  $user_roles = user_roles(TRUE);

  foreach ($user_roles as $role_name => $role_label) {
    if ($role_label == $name) {
      $recipient = (object) array();
      $recipient->type = 'role';
      $recipient->recipient = _privatemsg_roles_get_role_id($role_name, TRUE);
      $recipient->name = $role_name;
      $recipient->label = $role_label;
      return array(privatemsg_recipient_key($recipient) => $recipient);
    }
  }
}

/**
 * Get an role_id for a given role.
 *   Checks the role to role_id mapping, with an option to generate a mapping
 *   for a role.
 *
 * @param string $role_name
 *   The role that we need a role_id value for, defaults to anonymous.
 * @param bool $create
 *   Whether or not to create a role_id if one does not exist. Default false.
 *
 * @return int|null
 *   An integer pulled from config (and/or saved to config if needed), or NULL
 *   if no role_id found or created.
 *
 */
function _privatemsg_roles_get_role_id($role_name = BACKDROP_AUTHENTICATED_ROLE, $create = FALSE) {
  if ($role_name == BACKDROP_AUTHENTICATED_ROLE) {
    return 1;
  }
  $config = config('privatemsg_roles.settings');
  $role_id = $config->get('role_id.' . $role_name);
  if (is_numeric($role_id)) {
    return $role_id;
  }
  if (empty($role_id) && $create) {
    $rids = $config->get('role_id');
    $max = 2;
    if (is_array($rids)) {
      $max = max($rids) + 1;
    }
    $config->set('role_id.' . $role_name, $max);
    $config->save();
    return $max;
  }
  return NULL;
}

/**
 * Implements hook_user_role_insert().
 */
function privatemsg_roles_user_role_insert($role) {
  // Generate a role_id for the new role and save it to the mapping.
  _privatemsg_roles_get_role_id($role->name, TRUE);
}

/**
 * Implements hook_user_role_delete().
 */
function privatemsg_roles_user_role_delete($role) {
  config_clear('privatemsg_roles.settings', 'role_id.' . $role->name);
}
